# plugin管理
[[plugins]]
repo = 'Shougo/dein.vim'

# 非同期処理全般
[[plugins]]
repo = 'Shougo/vimproc.vim'

# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# j, k高速化
[[plugins]]
repo = 'rhysd/accelerated-jk'

# /検索強化
[[plugins]]
repo = 'osyo-manga/vim-anzu'

# f検索強化
[[plugins]]
repo = 'rhysd/clever-f.vim'

# 補完
[[plugins]]
repo = 'Shougo/neocomplcache.vim'

# 補完
[[plugins]]
repo = 'Shougo/neocomplcache-rsense.vim'

# 静的解析
[[plugins]]
repo = 'scrooloose/syntastic'

# 閉じ括弧とか補完
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
